package workbook.classwork.collections.task10_3;

public enum SecondNames {
    IVANOV, PETROV, SIDOROV, SMIRNOV, MALKIN, OVECHKIN, GRABOVSKY, PETROVSKY, BLINOV, KORJOV, SVETIN, IZMAILOV, IVANENKO, KUZMIN,
    KAMENSKY, RIABOV, LARIONOV, FEDOROV, ASTAHOV, VYBORNY, JOHNSON, ALFREDSON, CLARK, OTTIS, MATTHEWS, LINDROS, RENBERG, STEVENS
}
