package workbook2.lab10;

public enum ProductNames {
    WAFFLE, HAM, MUSHROOM, YEAST, GELATINE, GREASE, YOGHURT, COCOA, KVASS, KEFIR, SAUSAGE, CANDY, COFFEE, STARCH,
    CEREALS, CHICKEN, SODA, MAYONNAISE, MARGARINE, BUTTER, HONEY, WATER, MILK, FLOUR, MEAT, COOKIES, BEER, FISH,
    SALO, SUGAR, CREAM, JUICE, SALT, CHEESE, TOMATO, VINEGAR, POTATO, DUCK, TEA, PRUNES, CHOCOLATE, EGG;
}
