package workbook.classwork.emloyeeDatabase;

public enum LastNames {
    IVANOV, PETROV, SIDOROV, SMIRNOV, MALKIN, OVECHKIN, GRABOVSKY, PETROVSKY, BLINOV, KORJOV, SVETIN, IZMAILOV, IVANENKO, KUZMIN, KAMENSKY, RIABOV, LARIONOV, FEDOROV, ASTAHOV
}
