package workbook.classwork.emloyeeDatabase;

public enum ProjectNames {
    SIMPLE_DATABASE, INTERNET_SHOP, INTERNET_PORTAL, LARGE_DATABASE, ANDROID_APPLICATION, PRESENTATION_FORM,
    SIMPLE_FRONTEND, ADVANCED_FRONTEND, WINDOWS_APPLICATION, SOFT_UPDATE
}
